# Node.js with React (test)
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Use Node.js 10'

  - script: |
      npm install
      npm test
    displayName: 'npm install and test'

  - script: docker build -t clearlydefined/website:latest .
    displayName: 'Docker build'
